# Generated by Django 6.0.4 on 2026-05-02 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(choices=[('personal', 'Personal'), ('company', 'Company')], max_length=20)),
                ('asset_type', models.CharField(choices=[('none', 'None'), ('assets', 'Assets'), ('depreciation', 'Depreciation')], default='none', max_length=20)),
                ('functional_status', models.BooleanField(blank=True, help_text='True=Functional, False=Not functional, Null=Unknown', null=True)),
                ('urgency', models.CharField(choices=[('low', 'Low - Can wait'), ('medium', 'Medium - Flexible'), ('high', 'High - Sell soon')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold', 'Sold'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('sum_price', models.DecimalField(decimal_places=2, help_text='Original cost / Total investment', max_digits=10)),
                ('estimated_price', models.DecimalField(decimal_places=2, help_text='Current market value', max_digits=10)),
                ('tva_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-urgency', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Item Image',
                'verbose_name_plural': 'Item Images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_date', models.DateTimeField()),
                ('buyer_info', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_history', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Sale History',
                'verbose_name_plural': 'Sale Histories',
                'ordering': ['-sold_date'],
            },
        ),
    ]
