# Generated by Django 6.0.4 on 2026-05-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sales_platform',
            field=models.CharField(blank=True, choices=[('olx', 'OLX'), ('facebook', 'Facebook Marketplace'), ('vinted', 'Vinted'), ('local', 'Local/In-person'), ('other', 'Other')], help_text='Where you plan to sell this item', max_length=20, null=True),
        ),
    ]
