# Generated by Django 6.0.4 on 2026-05-02 01:38

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_sales_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sales_platform',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('olx', 'OLX'), ('facebook', 'Facebook Marketplace'), ('vinted', 'Vinted'), ('local', 'Local/In-person'), ('other', 'Other')], help_text='Where you plan to sell this item', max_length=31, null=True),
        ),
    ]
